/** @license React v0.0.0-experimental-3310209d0
 * react-server-dom-webpack-writer.browser.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var g=require("react");function k(a){for(var c="https://reactjs.org/docs/error-decoder.html?invariant="+a,d=1;d<arguments.length;d++)c+="&args[]="+encodeURIComponent(arguments[d]);return"Minified React error #"+a+"; visit "+c+" for the full message or use the non-minified dev environment for full errors and additional helpful warnings."}function l(a,c){a.enqueue(c);return 0<a.desiredSize}var n=new TextEncoder,q=JSON.stringify;
function r(a,c,d){a=q(d,a.toJSON);c="J"+c.toString(16)+":"+a+"\n";return n.encode(c)}var t=Symbol.for("react.module.reference"),u=60103,v=60107,x=60112,y=60115,z=60116;if("function"===typeof Symbol&&Symbol.for){var A=Symbol.for;u=A("react.element");v=A("react.fragment");x=A("react.forward_ref");y=A("react.memo");z=A("react.lazy")}var B=Array.isArray,D=g.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher;
function E(a,c,d){var b=[],e={destination:c,bundlerConfig:d,cache:new Map,nextChunkId:0,pendingChunks:0,pingedSegments:b,completedModuleChunks:[],completedJSONChunks:[],completedErrorChunks:[],writtenSymbols:new Map,writtenModules:new Map,flowing:!1,toJSON:function(a,b){return F(e,this,a,b)}};e.pendingChunks++;c=G(e,function(){return a});b.push(c);return e}
function H(a,c,d,b){if(null!==d&&void 0!==d)throw Error(k(379));if("function"===typeof a)return a(b);if("string"===typeof a)return[u,a,c,b];if("symbol"===typeof a)return a===v?b.children:[u,a,c,b];if(null!=a&&"object"===typeof a){if(a.$$typeof===t)return[u,a,c,b];switch(a.$$typeof){case x:return a=a.render,a(b,void 0);case y:return H(a.type,c,d,b)}}throw Error(k(351,I(a)));}
function G(a,c){var d={id:a.nextChunkId++,query:c,ping:function(){var b=a.pingedSegments;b.push(d);1===b.length&&J(a)}};return d}function K(a){return Object.prototype.toString.call(a).replace(/^\[object (.*)\]$/,function(a,d){return d})}function L(a){var c=JSON.stringify(a);return'"'+a+'"'===c?a:c}
function I(a){switch(typeof a){case "string":return JSON.stringify(10>=a.length?a:a.substr(0,10)+"...");case "object":if(B(a))return"[...]";a=K(a);return"Object"===a?"{...}":a;case "function":return"function";default:return String(a)}}
function M(a,c){if(B(a)){for(var d="[",b=0;b<a.length;b++){0<b&&(d+=", ");if(6<b){d+="...";break}var e=a[b];d=""+b===c&&"object"===typeof e&&null!==e?d+M(e):d+I(e)}return d+"]"}d="{";b=Object.keys(a);for(e=0;e<b.length;e++){0<e&&(d+=", ");if(6<e){d+="...";break}var f=b[e];d+=L(f)+": ";var m=a[f];d=f===c&&"object"===typeof m&&null!==m?d+M(m):d+I(m)}return d+"}"}
function F(a,c,d,b){switch(b){case u:return"$";case z:throw Error(k(352));}for(;"object"===typeof b&&null!==b&&b.$$typeof===u;){var e=b;try{b=H(e.type,e.key,e.ref,e.props)}catch(p){if("object"===typeof p&&null!==p&&"function"===typeof p.then)return a.pendingChunks++,a=G(a,function(){return b}),c=a.ping,p.then(c,c),"@"+a.id.toString(16);a.pendingChunks++;c=a.nextChunkId++;N(a,c,p);return"@"+c.toString(16)}}if(null===b)return null;if("object"===typeof b){if(b.$$typeof===t){e=b;var f=e.filepath+"#"+
e.name,m=a.writtenModules,C=m.get(f);if(void 0!==C)return c[0]===u&&"1"===d?"@"+C.toString(16):"$"+C.toString(16);try{var w=a.bundlerConfig[e.filepath][e.name];a.pendingChunks++;var h=a.nextChunkId++;O(a,h,w);m.set(f,h);return c[0]===u&&"1"===d?"@"+h.toString(16):"$"+h.toString(16)}catch(p){return a.pendingChunks++,c=a.nextChunkId++,N(a,c,p),"$"+c.toString(16)}}return b}if("string"===typeof b)return a="$"===b[0]||"@"===b[0]?"$"+b:b,a;if("boolean"===typeof b||"number"===typeof b||"undefined"===typeof b)return b;
if("function"===typeof b){if(/^on[A-Z]/.test(d))throw Error(k(374,L(d),M(c)));throw Error(k(375,L(d),b.displayName||b.name||"function",M(c)));}if("symbol"===typeof b){w=a.writtenSymbols;h=w.get(b);if(void 0!==h)return"$"+h.toString(16);h=b.description;if(Symbol.for(h)!==b)throw Error(k(376,b.description,L(d),M(c)));a.pendingChunks++;c=a.nextChunkId++;P(a,c,h);w.set(b,c);return"$"+c.toString(16)}if("bigint"===typeof b)throw Error(k(377,b,L(d),M(c)));throw Error(k(378,typeof b,L(d),M(c)));}
function N(a,c,d){var b="";try{if(d instanceof Error){var e=""+d.message;b=""+d.stack}else e="Error: "+d}catch(f){e="An error occurred but serializing the error message failed."}d={message:e,stack:b};c="E"+c.toString(16)+":"+q(d)+"\n";c=n.encode(c);a.completedErrorChunks.push(c)}function O(a,c,d){d=q(d);c="M"+c.toString(16)+":"+d+"\n";c=n.encode(c);a.completedModuleChunks.push(c)}function P(a,c,d){d=q(d);c="S"+c.toString(16)+":"+d+"\n";c=n.encode(c);a.completedModuleChunks.push(c)}
function Q(a,c){var d=c.query,b;try{for(b=d();"object"===typeof b&&null!==b&&b.$$typeof===u;)d=b,c.query=function(){return b},b=H(d.type,d.key,d.ref,d.props);var e=r(a,c.id,b);a.completedJSONChunks.push(e)}catch(f){"object"===typeof f&&null!==f&&"function"===typeof f.then?(a=c.ping,f.then(a,a)):N(a,c.id,f)}}function J(a){var c=D.current,d=R;D.current=S;R=a.cache;var b=a.pingedSegments;a.pingedSegments=[];for(var e=0;e<b.length;e++)Q(a,b[e]);a.flowing&&T(a);D.current=c;R=d}var U=!1;
function T(a){if(!U){U=!0;var c=a.destination;try{for(var d=a.completedModuleChunks,b=0;b<d.length;b++)if(a.pendingChunks--,!l(c,d[b])){a.flowing=!1;b++;break}d.splice(0,b);var e=a.completedJSONChunks;for(b=0;b<e.length;b++)if(a.pendingChunks--,!l(c,e[b])){a.flowing=!1;b++;break}e.splice(0,b);var f=a.completedErrorChunks;for(b=0;b<f.length;b++)if(a.pendingChunks--,!l(c,f[b])){a.flowing=!1;b++;break}f.splice(0,b)}finally{U=!1}0===a.pendingChunks&&c.close()}}function V(){throw Error(k(373));}
function W(){if(!R)throw Error(k(384));}var R=null,S={useMemo:function(a){return a()},useCallback:function(a){return a},useDebugValue:function(){},useDeferredValue:function(a){return a},useTransition:function(){return[function(){},!1]},getCacheForType:function(a){if(!R)throw Error(k(380));var c=R.get(a);void 0===c&&(c=a(),R.set(a,c));return c},readContext:V,useContext:V,useReducer:V,useRef:V,useState:V,useLayoutEffect:V,useImperativeHandle:V,useEffect:V,useOpaqueIdentifier:V,useMutableSource:V,useCacheRefresh:function(){return W}};
exports.renderToReadableStream=function(a,c){var d;return new ReadableStream({start:function(b){b=d=E(a,b,c);b.flowing=!0;J(b)},pull:function(){var a=d;a.flowing=!0;T(a)},cancel:function(){}})};
