/** @license React v0.0.0-experimental-3310209d0
 * react-server-dom-webpack-writer.node.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var g=require("react");function k(a){for(var b="https://reactjs.org/docs/error-decoder.html?invariant="+a,d=1;d<arguments.length;d++)b+="&args[]="+encodeURIComponent(arguments[d]);return"Minified React error #"+a+"; visit "+b+" for the full message or use the non-minified dev environment for full errors and additional helpful warnings."}var l=JSON.stringify;function n(a,b,d){a=l(d,a.toJSON);b="J"+b.toString(16)+":"+a+"\n";return Buffer.from(b,"utf8")}
var q=Symbol.for("react.module.reference"),r=60103,t=60107,u=60112,w=60115,x=60116;if("function"===typeof Symbol&&Symbol.for){var y=Symbol.for;r=y("react.element");t=y("react.fragment");u=y("react.forward_ref");w=y("react.memo");x=y("react.lazy")}var z=Array.isArray,B=g.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher;
function C(a,b,d){var c=[],e={destination:b,bundlerConfig:d,cache:new Map,nextChunkId:0,pendingChunks:0,pingedSegments:c,completedModuleChunks:[],completedJSONChunks:[],completedErrorChunks:[],writtenSymbols:new Map,writtenModules:new Map,flowing:!1,toJSON:function(a,b){return D(e,this,a,b)}};e.pendingChunks++;b=E(e,function(){return a});c.push(b);return e}
function F(a,b,d,c){if(null!==d&&void 0!==d)throw Error(k(379));if("function"===typeof a)return a(c);if("string"===typeof a)return[r,a,b,c];if("symbol"===typeof a)return a===t?c.children:[r,a,b,c];if(null!=a&&"object"===typeof a){if(a.$$typeof===q)return[r,a,b,c];switch(a.$$typeof){case u:return a=a.render,a(c,void 0);case w:return F(a.type,b,d,c)}}throw Error(k(351,G(a)));}function H(a,b){var d=a.pingedSegments;d.push(b);1===d.length&&setImmediate(function(){return I(a)})}
function E(a,b){var d={id:a.nextChunkId++,query:b,ping:function(){return H(a,d)}};return d}function J(a){return Object.prototype.toString.call(a).replace(/^\[object (.*)\]$/,function(a,d){return d})}function K(a){var b=JSON.stringify(a);return'"'+a+'"'===b?a:b}function G(a){switch(typeof a){case "string":return JSON.stringify(10>=a.length?a:a.substr(0,10)+"...");case "object":if(z(a))return"[...]";a=J(a);return"Object"===a?"{...}":a;case "function":return"function";default:return String(a)}}
function L(a,b){if(z(a)){for(var d="[",c=0;c<a.length;c++){0<c&&(d+=", ");if(6<c){d+="...";break}var e=a[c];d=""+c===b&&"object"===typeof e&&null!==e?d+L(e):d+G(e)}return d+"]"}d="{";c=Object.keys(a);for(e=0;e<c.length;e++){0<e&&(d+=", ");if(6<e){d+="...";break}var f=c[e];d+=K(f)+": ";var m=a[f];d=f===b&&"object"===typeof m&&null!==m?d+L(m):d+G(m)}return d+"}"}
function D(a,b,d,c){switch(c){case r:return"$";case x:throw Error(k(352));}for(;"object"===typeof c&&null!==c&&c.$$typeof===r;){var e=c;try{c=F(e.type,e.key,e.ref,e.props)}catch(p){if("object"===typeof p&&null!==p&&"function"===typeof p.then)return a.pendingChunks++,a=E(a,function(){return c}),b=a.ping,p.then(b,b),"@"+a.id.toString(16);a.pendingChunks++;b=a.nextChunkId++;M(a,b,p);return"@"+b.toString(16)}}if(null===c)return null;if("object"===typeof c){if(c.$$typeof===q){e=c;var f=e.filepath+"#"+
e.name,m=a.writtenModules,A=m.get(f);if(void 0!==A)return b[0]===r&&"1"===d?"@"+A.toString(16):"$"+A.toString(16);try{var v=a.bundlerConfig[e.filepath][e.name];a.pendingChunks++;var h=a.nextChunkId++;N(a,h,v);m.set(f,h);return b[0]===r&&"1"===d?"@"+h.toString(16):"$"+h.toString(16)}catch(p){return a.pendingChunks++,b=a.nextChunkId++,M(a,b,p),"$"+b.toString(16)}}return c}if("string"===typeof c)return a="$"===c[0]||"@"===c[0]?"$"+c:c,a;if("boolean"===typeof c||"number"===typeof c||"undefined"===typeof c)return c;
if("function"===typeof c){if(/^on[A-Z]/.test(d))throw Error(k(374,K(d),L(b)));throw Error(k(375,K(d),c.displayName||c.name||"function",L(b)));}if("symbol"===typeof c){v=a.writtenSymbols;h=v.get(c);if(void 0!==h)return"$"+h.toString(16);h=c.description;if(Symbol.for(h)!==c)throw Error(k(376,c.description,K(d),L(b)));a.pendingChunks++;b=a.nextChunkId++;O(a,b,h);v.set(c,b);return"$"+b.toString(16)}if("bigint"===typeof c)throw Error(k(377,c,K(d),L(b)));throw Error(k(378,typeof c,K(d),L(b)));}
function M(a,b,d){var c="";try{if(d instanceof Error){var e=""+d.message;c=""+d.stack}else e="Error: "+d}catch(f){e="An error occurred but serializing the error message failed."}d={message:e,stack:c};b="E"+b.toString(16)+":"+l(d)+"\n";b=Buffer.from(b,"utf8");a.completedErrorChunks.push(b)}function N(a,b,d){d=l(d);b="M"+b.toString(16)+":"+d+"\n";b=Buffer.from(b,"utf8");a.completedModuleChunks.push(b)}
function O(a,b,d){d=l(d);b="S"+b.toString(16)+":"+d+"\n";b=Buffer.from(b,"utf8");a.completedModuleChunks.push(b)}function P(a,b){var d=b.query,c;try{for(c=d();"object"===typeof c&&null!==c&&c.$$typeof===r;)d=c,b.query=function(){return c},c=F(d.type,d.key,d.ref,d.props);var e=n(a,b.id,c);a.completedJSONChunks.push(e)}catch(f){"object"===typeof f&&null!==f&&"function"===typeof f.then?(a=b.ping,f.then(a,a)):M(a,b.id,f)}}
function I(a){var b=B.current,d=Q;B.current=R;Q=a.cache;var c=a.pingedSegments;a.pingedSegments=[];for(var e=0;e<c.length;e++)P(a,c[e]);a.flowing&&S(a);B.current=b;Q=d}var T=!1;
function S(a){if(!T){T=!0;var b=a.destination;"function"===typeof b.cork&&b.cork();try{for(var d=a.completedModuleChunks,c=0;c<d.length;c++)if(a.pendingChunks--,!b.write(d[c])){a.flowing=!1;c++;break}d.splice(0,c);var e=a.completedJSONChunks;for(c=0;c<e.length;c++)if(a.pendingChunks--,!b.write(e[c])){a.flowing=!1;c++;break}e.splice(0,c);var f=a.completedErrorChunks;for(c=0;c<f.length;c++)if(a.pendingChunks--,!b.write(f[c])){a.flowing=!1;c++;break}f.splice(0,c)}finally{T=!1,"function"===typeof b.uncork&&
b.uncork()}"function"===typeof b.flush&&"function"!==typeof b.flushHeaders&&b.flush();0===a.pendingChunks&&b.end()}}function U(a){a.flowing=!0;setImmediate(function(){return I(a)})}function V(){throw Error(k(373));}function W(){if(!Q)throw Error(k(384));}
var Q=null,R={useMemo:function(a){return a()},useCallback:function(a){return a},useDebugValue:function(){},useDeferredValue:function(a){return a},useTransition:function(){return[function(){},!1]},getCacheForType:function(a){if(!Q)throw Error(k(380));var b=Q.get(a);void 0===b&&(b=a(),Q.set(a,b));return b},readContext:V,useContext:V,useReducer:V,useRef:V,useState:V,useLayoutEffect:V,useImperativeHandle:V,useEffect:V,useOpaqueIdentifier:V,useMutableSource:V,useCacheRefresh:function(){return W}};
function X(a,b){return function(){b.flowing=!0;S(b)}}exports.pipeToNodeWritable=function(a,b,d){a=C(a,b,d);b.on("drain",X(b,a));U(a)};
