/** @license React v0.0.0-experimental-3310209d0
 * react-server-dom-webpack-writer.browser.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
(function(){'use strict';(function(k,t){"object"===typeof exports&&"undefined"!==typeof module?t(exports,require("react")):"function"===typeof define&&define.amd?define(["exports","react"],t):(k=k||self,t(k.ReactServerDOMWriter={},k.React))})(this,function(k,t){function g(a){for(var c="https://reactjs.org/docs/error-decoder.html?invariant="+a,d=1;d<arguments.length;d++)c+="&args[]="+encodeURIComponent(arguments[d]);return"Minified React error #"+a+"; visit "+c+" for the full message or use the non-minified dev environment for full errors and additional helpful warnings."}
function x(a,c){a.enqueue(c);return 0<a.desiredSize}function M(a,c,d){a=v(d,a.toJSON);c="J"+c.toString(16)+":"+a+"\n";return w.encode(c)}function N(a,c,d){var b=[],e={destination:c,bundlerConfig:d,cache:new Map,nextChunkId:0,pendingChunks:0,pingedSegments:b,completedModuleChunks:[],completedJSONChunks:[],completedErrorChunks:[],writtenSymbols:new Map,writtenModules:new Map,flowing:!1,toJSON:function(a,b){return O(e,this,a,b)}};e.pendingChunks++;c=D(e,function(){return a});b.push(c);return e}function y(a,
c,d,b){if(null!==d&&void 0!==d)throw Error(g(379));if("function"===typeof a)return a(b);if("string"===typeof a)return[n,a,c,b];if("symbol"===typeof a)return a===E?b.children:[n,a,c,b];if(null!=a&&"object"===typeof a){if(a.$$typeof===F)return[n,a,c,b];switch(a.$$typeof){case G:return a=a.render,a(b,void 0);case H:return y(a.type,c,d,b)}}throw Error(g(351,z(a)));}function D(a,c){var d={id:a.nextChunkId++,query:c,ping:function(){var b=a.pingedSegments;b.push(d);1===b.length&&I(a)}};return d}function P(a){return Object.prototype.toString.call(a).replace(/^\[object (.*)\]$/,
function(a,d){return d})}function r(a){var c=JSON.stringify(a);return'"'+a+'"'===c?a:c}function z(a){switch(typeof a){case "string":return JSON.stringify(10>=a.length?a:a.substr(0,10)+"...");case "object":if(J(a))return"[...]";a=P(a);return"Object"===a?"{...}":a;case "function":return"function";default:return String(a)}}function p(a,c){if(J(a)){for(var d="[",b=0;b<a.length;b++){0<b&&(d+=", ");if(6<b){d+="...";break}var e=a[b];d=""+b===c&&"object"===typeof e&&null!==e?d+p(e):d+z(e)}return d+"]"}d=
"{";b=Object.keys(a);for(e=0;e<b.length;e++){0<e&&(d+=", ");if(6<e){d+="...";break}var f=b[e];d+=r(f)+": ";var g=a[f];d=f===c&&"object"===typeof g&&null!==g?d+p(g):d+z(g)}return d+"}"}function O(a,c,d,b){switch(b){case n:return"$";case K:throw Error(g(352));}for(;"object"===typeof b&&null!==b&&b.$$typeof===n;){var e=b;try{b=y(e.type,e.key,e.ref,e.props)}catch(q){if("object"===typeof q&&null!==q&&"function"===typeof q.then)return a.pendingChunks++,a=D(a,function(){return b}),c=a.ping,q.then(c,c),"@"+
a.id.toString(16);a.pendingChunks++;c=a.nextChunkId++;A(a,c,q);return"@"+c.toString(16)}}if(null===b)return null;if("object"===typeof b){if(b.$$typeof===F){e=b;var f=e.filepath+"#"+e.name,h=a.writtenModules,l=h.get(f);if(void 0!==l)return c[0]===n&&"1"===d?"@"+l.toString(16):"$"+l.toString(16);try{var k=a.bundlerConfig[e.filepath][e.name];a.pendingChunks++;var m=a.nextChunkId++;Q(a,m,k);h.set(f,m);return c[0]===n&&"1"===d?"@"+m.toString(16):"$"+m.toString(16)}catch(q){return a.pendingChunks++,c=a.nextChunkId++,
A(a,c,q),"$"+c.toString(16)}}return b}if("string"===typeof b)return a="$"===b[0]||"@"===b[0]?"$"+b:b,a;if("boolean"===typeof b||"number"===typeof b||"undefined"===typeof b)return b;if("function"===typeof b){if(/^on[A-Z]/.test(d))throw Error(g(374,r(d),p(c)));throw Error(g(375,r(d),b.displayName||b.name||"function",p(c)));}if("symbol"===typeof b){k=a.writtenSymbols;m=k.get(b);if(void 0!==m)return"$"+m.toString(16);m=b.description;if(Symbol.for(m)!==b)throw Error(g(376,b.description,r(d),p(c)));a.pendingChunks++;
c=a.nextChunkId++;R(a,c,m);k.set(b,c);return"$"+c.toString(16)}if("bigint"===typeof b)throw Error(g(377,b,r(d),p(c)));throw Error(g(378,typeof b,r(d),p(c)));}function A(a,c,d){var b="";try{if(d instanceof Error){var e=""+d.message;b=""+d.stack}else e="Error: "+d}catch(f){e="An error occurred but serializing the error message failed."}d={message:e,stack:b};c="E"+c.toString(16)+":"+v(d)+"\n";c=w.encode(c);a.completedErrorChunks.push(c)}function Q(a,c,d){d=v(d);c="M"+c.toString(16)+":"+d+"\n";c=w.encode(c);
a.completedModuleChunks.push(c)}function R(a,c,d){d=v(d);c="S"+c.toString(16)+":"+d+"\n";c=w.encode(c);a.completedModuleChunks.push(c)}function S(a,c){var d=c.query,b;try{for(b=d();"object"===typeof b&&null!==b&&b.$$typeof===n;)d=b,c.query=function(){return b},b=y(d.type,d.key,d.ref,d.props);var e=M(a,c.id,b);a.completedJSONChunks.push(e)}catch(f){"object"===typeof f&&null!==f&&"function"===typeof f.then?(a=c.ping,f.then(a,a)):A(a,c.id,f)}}function I(a){var c=B.current,d=l;B.current=T;l=a.cache;var b=
a.pingedSegments;a.pingedSegments=[];for(var e=0;e<b.length;e++)S(a,b[e]);a.flowing&&L(a);B.current=c;l=d}function L(a){if(!C){C=!0;var c=a.destination;try{for(var d=a.completedModuleChunks,b=0;b<d.length;b++)if(a.pendingChunks--,!x(c,d[b])){a.flowing=!1;b++;break}d.splice(0,b);var e=a.completedJSONChunks;for(b=0;b<e.length;b++)if(a.pendingChunks--,!x(c,e[b])){a.flowing=!1;b++;break}e.splice(0,b);var f=a.completedErrorChunks;for(b=0;b<f.length;b++)if(a.pendingChunks--,!x(c,f[b])){a.flowing=!1;b++;
break}f.splice(0,b)}finally{C=!1}0===a.pendingChunks&&c.close()}}function h(){throw Error(g(373));}function U(){if(!l)throw Error(g(384));}var w=new TextEncoder,v=JSON.stringify,F=Symbol.for("react.module.reference"),n=60103,E=60107,G=60112,H=60115,K=60116;if("function"===typeof Symbol&&Symbol.for){var u=Symbol.for;n=u("react.element");E=u("react.fragment");G=u("react.forward_ref");H=u("react.memo");K=u("react.lazy")}var J=Array.isArray,B=t.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher,
C=!1,l=null,T={useMemo:function(a){return a()},useCallback:function(a){return a},useDebugValue:function(){},useDeferredValue:function(a){return a},useTransition:function(){return[function(){},!1]},getCacheForType:function(a){if(!l)throw Error(g(380));var c=l.get(a);void 0===c&&(c=a(),l.set(a,c));return c},readContext:h,useContext:h,useReducer:h,useRef:h,useState:h,useLayoutEffect:h,useImperativeHandle:h,useEffect:h,useOpaqueIdentifier:h,useMutableSource:h,useCacheRefresh:function(){return U}};k.renderToReadableStream=
function(a,c){var d;return new ReadableStream({start:function(b){b=d=N(a,b,c);b.flowing=!0;I(b)},pull:function(a){a=d;a.flowing=!0;L(a)},cancel:function(a){}})}});
})();
